
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module PE42(

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



// LED0 = O1, LED1 = O0, LED2 = V
assign LEDR[0] = SW[2] | SW[3];
assign LEDR[1] = SW[3] | ((~SW[2]) & SW[1]); 
assign LEDR[2] = SW[3] | SW[2] | SW[1] | SW[0]; 


endmodule
