
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Part1(

	
	 input  [7:0] A,    
    input  [7:0] B,    
    input  cin,        
    output [7:0] S,    
    output cout,       
    output Overflow    
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================
 
    ripple_carry_adder_8bit adder(
        .A(A),
        .B(B),
        .cin(cin),
        .S(S),
        .cout(cout),
        .Overflow(Overflow)
    );
endmodule
