
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================


module PE83(
    input  [7:0] SW, //SWshuruinput
    output [3:0] LEDR//LEDR[3]=O2, LEDR[2]=O1, LEDR[1]=O0, LEDR[0]=V
);

    wire [2:0] high_LEDR;
    wire [2:0] low_LEDR;
    
    PE42 high_PE42 (
        .SW(SW[7:4]),
        .LEDR(high_LEDR)
    );

    PE42 low_PE42 (
        .SW(SW[3:0]),
        .LEDR(low_LEDR)
    );
	 
    assign LEDR[3] = high_LEDR[2];                           // O2 = V_high
    assign {LEDR[2], LEDR[1]} = (high_LEDR[2]) ? high_LEDR[1:0] : low_LEDR[1:0]; // If V_high=1, choose high_LEDR[1:0], else low_LEDR[1:0]
    assign LEDR[0] = high_LEDR[2] | low_LEDR[2];              // V = V_high | V_low


endmodule

module PE42(

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



// LED0 = O1, LED1 = O0, LED2 = V
assign LEDR[1] = SW[2] | SW[3];
assign LEDR[0] = SW[3] | ((~SW[2]) & SW[1]); 
assign LEDR[2] = SW[3] | SW[2] | SW[1] | SW[0]; 


endmodule
